"""empty message

Revision ID: 98b04b7d40a7
Revises: c7cc3f48bde8
Create Date: 2020-04-02 22:59:50.777895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b04b7d40a7'
down_revision = 'c7cc3f48bde8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Employees',
    sa.Column('employeeId', sa.INTEGER(), server_default=sa.text('nextval(\'"Employees_employeeId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('ho', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ten', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('employeeId', name='Employees_pkey')
    )
    # ### end Alembic commands ###
