"""empty message

Revision ID: c7cc3f48bde8
Revises: 5456fe182ab3
Create Date: 2020-03-31 11:46:19.314883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7cc3f48bde8'
down_revision = '5456fe182ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkin',
    sa.Column('employeeId', sa.Integer(), nullable=False),
    sa.Column('checkinDate', sa.Date(), nullable=False),
    sa.Column('checkinTime', sa.DateTime(), nullable=True),
    sa.Column('checkoutTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('employeeId', 'checkinDate')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkin')
    # ### end Alembic commands ###
